### ISSUE TITLE
Does not seem to work in IE11

### ISSUE THREAD

**Issue by timkorona** [willhoag/scroll-to-element#9]
Works great in Chrome.  Unfortunately we have to support a variety of browsers.  When we try to run using IE11 it does not appear to work.  Has this been tested in IE?

**Comment by willhoag** [comment]
I haven't had a chance to test in IE. Is there an error you can show to help debug?

This package should probably have automated testing at this point. Will try to add soon, but it's low on my priorities at the moment, so PR's are welcome.

**Comment by timkorona** [comment]
Will,

Thanks for the reply.  Unfortunately, due to project commitments we were no able to spend a lot of time looking into why it did not work with IE.  There were no obvious errors displayed, it just did not work.  We were forced to try another plugin.

I would love to spend some time looking into it but as you pointed out, priorities.  If I get the chance and find anything useful I will be sure to post it here.

Thanks again.

**Comment by willhoag** [comment]
You're welcome. I'll leave this issue open and try to have a look at it soon. Thanks for pointing it out.

![thanks](https://media3.giphy.com/media/3oEdva9BUHPIs2SkGk/200w.gif)

**Comment by juliabower** [comment]
I'm also having this issue. Here's what I could find:

Error: SCRIPT65535: Invalid calling object

Looks like this error is being hit in scroll-to, index.js line 46

`  // animate
  function animate() {
    raf(animate);
    tween.update();
  }
`
Not sure if I'm missing some sort of polyfill etc
Any suggestions?
Thanks

**Comment by cwklausing** [comment]
Hey Julia, I had the exact same issue; however, I realized that the error only occurs in IE when using webpack dev server (same thing was mentioned in [this thread](https://github.com/jquense/react-widgets/issues/91)). When I checked in production there wasn't any issue. 
Hope this helps.

**Comment by asso1985** [comment]
IE11 does not support `Object.assign`

tween.js line 15

`this._curr = Object.assign({}, this._from);`

**Comment by willhoag** [comment]
Pull request for fix. Needs testing. https://github.com/willhoag/scroll-to-element/pull/11
